### ISSUE TITLE
Setup failed for senseme: Could not set up all dependencies.

### ISSUE THREAD

**Issue by dylancopeland** [mikelawrence/homeassistant-custom-components#1]
Hello,

Thanks for this great component.

I am currently running into an issue that prevents the component to initialize. I've just upgraded to HA 0.95.4 and am attempting to get the senseme component working. The following line is output the logs when starting HA:

```
Setup failed for senseme: Could not set up all dependencies.
```

It seems that the component is unable to install the senseme library. Is there a way to get more log output to determine what exactly is failing? The readme states that senseme should be installed automatically by HA, so I only want to install it manually as a last resort.

For what it's worth, the component previously worked when running HA 0.92.0.

**Edit:**
The component from c692e0bc05b6acb1ec00a78f5823a04a8c18837d currently works with HA 0.95.4. I just can't seem to get the version from 87f3f013cf1b13a7651b5c0150a5204b16fc6f1e to work.

**Comment by mikelawrence** [comment]
When upgrading to the new directory structure for Home Assistant I accidentally left mqtt as a dependency for the senseme component when I copied the manifest file from another component.

Give the latest commit a try. It should work now.

**Comment by dylancopeland** [comment]
The latest commit works great. Thank you again for the work on this!
