### ISSUE TITLE
Deley

### ISSUE THREAD

**Issue by johntdyer** [mikelawrence/homeassistant-custom-components#2]
Hello,

 I am trying to use your host / client config to make setting up a remote zwave host easier.  It seems to work but it takes a while to actually work quickly on the client host.  The first dozen or so attempts yield no results and then all of a sudden its increadibly responsive on the switch from that point forward.  on the host I am watching the zwave log and the first dozen toggles from the client do nothing and then all of a sudden it works and from that point forward it works everytime.. any thoughts ?

**Comment by mikelawrence** [comment]
Can you show me your config (just the sections related to my components)? 
Are you sharing the zwave.* states with my components? (Not a good idea)
You say the first dozen don't work but then it starts working. Does it work until the next reboot or is there something else you are doing? 
You are using a Z-Wave stick not an ISY-994 correct?

**Comment by johntdyer** [comment]
I was not setting includes so does this mean I was sharing the states?  How do I not share the states?  

Yes I am using a Aeontec stick, not a ISY-994

Also ignore what I said about the first dozen attempts, that appears to not be thje case... it seems to work intermittently at best. 

Thanks

**Comment by mikelawrence** [comment]
Previously I said states but meant entities.
Without your configuration I will have to guess at what you are doing.

Sounds like you are sharing all entities between the two Home Assistant instances. I have never done that. How many entities are you sharing?

Are all shared entities across both Home Assistant instances unique? Having the same entity name (switch.hallway) on both Home Assistant instances will cause problems.

Sharing zwave.* entities can cause a problem if you have zwave on both instances of Home Assistant. `Node_ids` will get mixed up between the two Home Assistant instances. I do not recommend sharing zwave.* entities.

Try sharing only a few specific entities (i.e. binary_sensor.hallway_motion) as an experiment to see if the sharing works better. Keep in mind if you previously shared everything your MQTT server will be polluted with a bunch of entities. So change `base_topic:` or delete the MQTT database and start over.

**Comment by mikelawrence** [comment]
Closing due to lack of response.
